ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TENANT_ADMIN';

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
